enum Endpoints {
  login,
  register,
  sendOtp,
  forgetPassword,
  verifyOtp,
  addRestaurant,
  getAllRestaurant,
  getRestaurantById,
  updateRestaurant,
  updateRestaurantOpentStatus,
  addDish,
  updateDish,
  deleteDish,
  updateDishStatus,
  getAllDishByRestaurant,
  getDishById,
  addItemToFoodCart,
  removeOneQuantityFromFoodCart,
  removeAllFromFoodCart,
  getAllFromFoodCart,
  removeOneItemFromFoodCart,
  createFoodOrder,
  paymentVerificationForFood,
  addTemple,
  deleteTemple,
  getAllTemple,
  getTmpleById,
  deleteTempleById,
  getUserProfile,
  updateProfilePictuce,
  updateUserProfile,
  updatePassword,
  addGuide,
  getGuideById,
  updateGuide,
  getAllGuide,
  deleteGuide
}

const Map<Endpoints, String> endpointRawValues = {
  // AUTHENTICATION
  Endpoints.login: "/api/v1/auth/login",
  Endpoints.register: "/api/v1/auth/register",
  Endpoints.sendOtp: "/api/v1/auth/sendOtp",
  Endpoints.forgetPassword: "/api/v1/auth/resetPassword",
  Endpoints.verifyOtp: "/api/v1/auth/verifyOtp",
  Endpoints.addRestaurant: "/api/v1/restaurant/register",
  Endpoints.getAllRestaurant: "/api/v1/restaurant",
  Endpoints.getRestaurantById: "/api/v1/restaurant",
  Endpoints.updateRestaurantOpentStatus: "/api/v1/restaurant/update",
  Endpoints.addDish: "/api/v1/dish/add/restaurant",
  Endpoints.getAllDishByRestaurant: "/api/v1/dish/restaurant",
  Endpoints.getDishById: "/api/v1/dish",
  Endpoints.deleteDish: "/api/v1/dish/delete",
  Endpoints.addItemToFoodCart: "/api/v1/food/cart/add",
  Endpoints.removeOneQuantityFromFoodCart: "/api/v1/food/cart/remove-one",
  Endpoints.removeAllFromFoodCart: "/api/v1/food/cart/all",
  Endpoints.getAllFromFoodCart: "/api/v1/food/cart/all",
  Endpoints.removeOneItemFromFoodCart: "/api/v1/food/cart/delete",
  Endpoints.createFoodOrder: "/api/v1/food/order/create",
  Endpoints.paymentVerificationForFood: "/api/v1/food/order/payment/verify",
  Endpoints.addTemple: "/api/v1/temple/add",
  Endpoints.getAllTemple: "/api/v1/temple/all",
  Endpoints.getTmpleById: "/api/v1/temple",
  Endpoints.deleteTempleById: "/api/v1/temple/delete",
  Endpoints.getUserProfile: "/api/v1/user",
  Endpoints.updateProfilePictuce: "/api/v1/user/edit/image",
  Endpoints.updateUserProfile: "/api/v1/user/edit",
  Endpoints.updatePassword: "/api/v1/user/edit/password",
  Endpoints.addGuide: "/api/v1/guide/register",
  Endpoints.getAllGuide: "/api/v1/guide/all",
  Endpoints.getGuideById: "/api/v1/guide",
  Endpoints.deleteGuide: "/api/v1/guide",
  Endpoints.updateGuide: "/api/v1/guide",
};
